/** Product configuration. Private destinations are supplied by environment variables. */
export const config = {
  name: 'BLANK HONEY',
  description: '记录一些值得停留的瞬间。代码、远行，以及日常的缝隙。',
  about: '写代码，也写一些没有用途的句子。记录远行，和日常的缝隙。',
  githubUrl: 'https://github.com/blankhoney',
  demoContent: false,
  sayings: ['Tempus fugit', 'Labor omnia vincit', 'Ars longa, vita brevis', 'Per aspera ad astra'],
  navigation: [
    { href: '/articles/', label: '文章', en: 'ARTICLES' },
    { href: '/probe/', label: '探针', en: 'PROBE' },
    { href: '/map/', label: '地图', en: 'MAP' },
    { href: '/graph/', label: '图谱', en: 'GRAPH' },
    { href: '/tools/', label: '工具', en: 'TOOLS' },
    { href: '/lab/', label: '实验室', en: 'LAB' },
  ],
  categories: [
    { slug: 'daily', name: '日常' },
    { slug: 'engineering', name: '工程' },
    { slug: 'papers', name: '论文笔记' },
    { slug: 'tutorials', name: '教程' },
    { slug: 'travel', name: '旅行' },
    { slug: 'design', name: '设计' },
    { slug: 'thoughts', name: '感悟' },
  ],
  hero: [
    { id: 'io724', name: '流体墨迹', source: 'https://io724.com' },
    { id: 'miniload', name: '像素云', source: 'https://miniload.top' },
    { id: 'isaca', name: '错层索引', source: 'https://isaca.pro' },
    { id: 'yantao', name: '代码札记', source: 'https://yantao.wiki' },
    // ios25span.com is unavailable; add its verified effect here when the reference returns.
  ],
  particles: { desktop: 1100, mobile: 420, light: 240 },
  map: {
    tileUrl: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: '© OpenStreetMap contributors',
    attributionUrl: 'https://www.openstreetmap.org/copyright',
    maxZoom: 19,
  },
  radio: [
    {
      id: 'piano-01',
      name: '静心钢琴 · Meditation Impromptu 01',
      source: 'direct' as 'direct' | 'rss',
      urlEnv: 'RADIO_PIANO_01_URL',
      url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Meditation%20Impromptu%2001.mp3',
    },
    {
      id: 'piano-02',
      name: '缓缓流动 · Meditation Impromptu 02',
      source: 'direct' as 'direct' | 'rss',
      urlEnv: 'RADIO_PIANO_02_URL',
      url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Meditation%20Impromptu%2002.mp3',
    },
    {
      id: 'dream',
      name: '轻柔节拍 · Dream Culture',
      source: 'direct' as 'direct' | 'rss',
      urlEnv: 'RADIO_DREAM_URL',
      url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dream%20Culture.mp3',
    },
  ],
  // Each local entry is bundled with its own assets on the separate lab origin.
  tools: [
    {
      slug: 'archive',
      name: '压缩小箱',
      description: '把文件装进 ZIP、7z，或打开压缩包取出需要的内容。',
      urlEnv: 'TOOL_ARCHIVE_URL',
      html: 'src/tools/archive/index.html',
    },
    {
      slug: 'image-crop',
      name: '图片裁切',
      description: '转一转、裁一裁，留下刚刚好的画面，再下载。',
      urlEnv: 'TOOL_IMAGE_CROP_URL',
      html: 'src/tools/image-crop/index.html',
    },
    {
      slug: 'markdown',
      name: 'Markdown 书桌',
      description: '放下一份 Markdown，在安静的纸面上读它。',
      urlEnv: 'TOOL_MARKDOWN_URL',
      html: 'src/tools/markdown/index.html',
    },
    {
      slug: 'luck',
      name: '公平好运',
      description: '投骰子，抛硬币。每一面都有相同的机会。',
      urlEnv: 'TOOL_LUCK_URL',
      html: 'src/tools/luck/index.html',
    },
    {
      slug: 'fortune',
      name: '今日小签',
      description: '看看四柱与节气，再抽一份仅供娱乐的今日小签。',
      urlEnv: 'TOOL_FORTUNE_URL',
      html: 'src/tools/fortune/index.html',
    },
  ],
  experiments: [
    {
      slug: 'paper',
      name: 'PAPER STUDY',
      description: '一张纸，一道折痕。观察光线经过纸背的过程。',
      urlEnv: 'LAB_PAPER_URL',
      html: 'examples/paper.html',
    },
  ],
} as const;
